# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
baseURL = "https://aquikos.github.io/wiki/"
defaultContentLanguage = "en"
languageCode = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[author]
name = "Aquikos"
image = "/images/pfp_transparent.png"
headline = "Hi"
bio = "Hi"
links = [
  {}
]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
